name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Set environment variable for Spring profile
        run: echo "SPRING_PROFILES_ACTIVE=local" >> $GITHUB_ENV

      - name: Verify Java Version
        run: java -version

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests with debug logs
        run: mvn -X test